### ISSUE TITLE
Support Jenkins CLI environment variables

### ISSUE THREAD

**Issue by HoldenLucas** [ckipp01/nvim-jenkinsfile-linter#4]
The [Jenkins CLI guide](https://www.jenkins.io/doc/book/managing/cli/#using-the-cli-client) suggests setting `$JENKINS_URL`, `$JENKINS_USER_ID`, and `$JENKINS_API_TOKEN` to avoid having to pass them as command line arguments.

However, this plugin expects `$JENKINS_HOST`, `$JENKINS_USERNAME`, and `$JENKINS_TOKEN`, respectively.

Would you be opposed to supporting the official CLI environment variables? I would be happy to do the legwork, I just wanted to confirm first.

**Comment by ckipp01** [comment]
Hey @HoldenLucas! 

> Would you be opposed to supporting the official CLI environment variables? I would be happy to do the legwork, I just wanted to confirm first.

Sure, to be honest I'm not sure why I picked those names over the actual ones that are suggested. One thing I'd recommend though is to advertise the recommend ones but still keep the old ones and just alias them. Mainly I want to avoid this breaking for anyone that already has those set.

**Comment by Smaug123** [comment]
Just a quick note that this user prefers the old convention, not the JENKINS_URL etc, because the existence of JENKINS_URL is a standard heuristic for determining whether the current environment is a Jenkins job. (I just spent a long time debugging a problem which ended up being "something thought my shell was Jenkins and therefore was noninteractive" for this reason.)
